# Generated by Django 4.2.26 on 2026-01-11 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('subject', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_At', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('Section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.section')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.class')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
