# Generated by Django 4.2.26 on 2026-01-11 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='updated_at',
            new_name='updated_At',
        ),
    ]
