# Generated by Django 4.2.26 on 2026-01-12 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_rename_updated_at_assignment_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='Section',
            new_name='section',
        ),
    ]
