# Generated by Django 4.2.26 on 2026-01-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_rename_section_assignment_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='updated_At',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
