# Generated by Django 4.2.26 on 2026-01-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_assignmentsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/submissions/'),
        ),
    ]
