# Generated by Django 4.2.26 on 2026-01-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_alter_assignmentsubmission_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
